#!/usr/bin/env bash
# python_interpreter.sh — Display instructions for configuring the Python interpreter in VS Code
echo "═══════════════════════════════════════════════════════════"
echo " Configure Python Interpreter in VS Code"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo " After VS Code opens the Propello workspace, set the Python"
echo " interpreter to the 'erc' pyenv virtualenv:"
echo ""
echo "  1. Press Ctrl+Shift+P"
echo "     → type: Python: Select Interpreter"
echo "     → press Enter"
echo ""
echo "  2. Choose the interpreter that shows:"
echo "       ~/.pyenv/versions/erc/bin/python"
echo "     It may appear as:"
echo "       Python 3.9.x ('erc': pyenv)"
echo ""
echo "  3. If it does not appear, click 'Enter interpreter path'"
echo "     and paste: ~/.pyenv/versions/erc/bin/python"
echo ""
echo "  4. Reload the VS Code window if prompted (Ctrl+Shift+P → Reload Window)"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo " This step completes automatically."
echo "═══════════════════════════════════════════════════════════"
exit 0
